-- Seed Role Permissions
-- Owner has all permissions
INSERT INTO role_permissions (role, permission) VALUES
  -- Owner permissions (full access)
  ('owner', 'dashboard.view'),
  ('owner', 'products.read'),
  ('owner', 'products.write'),
  ('owner', 'products.delete'),
  ('owner', 'stock.read'),
  ('owner', 'stock.write'),
  ('owner', 'stock.adjust'),
  ('owner', 'packaging.read'),
  ('owner', 'packaging.write'),
  ('owner', 'suppliers.read'),
  ('owner', 'suppliers.write'),
  ('owner', 'purchases.read'),
  ('owner', 'purchases.write'),
  ('owner', 'purchases.receive'),
  ('owner', 'clients.read'),
  ('owner', 'clients.write'),
  ('owner', 'clients.delete'),
  ('owner', 'sales.read'),
  ('owner', 'sales.write'),
  ('owner', 'sales.cancel'),
  ('owner', 'payments.read'),
  ('owner', 'payments.write'),
  ('owner', 'deliveries.read'),
  ('owner', 'deliveries.write'),
  ('owner', 'vehicles.read'),
  ('owner', 'vehicles.write'),
  ('owner', 'reports.view'),
  ('owner', 'reports.export'),
  ('owner', 'alerts.read'),
  ('owner', 'alerts.manage'),
  ('owner', 'users.read'),
  ('owner', 'users.write'),
  ('owner', 'users.delete'),
  ('owner', 'settings.read'),
  ('owner', 'settings.write'),
  ('owner', 'subscription.manage'),
  
  -- Manager permissions
  ('manager', 'dashboard.view'),
  ('manager', 'products.read'),
  ('manager', 'products.write'),
  ('manager', 'stock.read'),
  ('manager', 'stock.write'),
  ('manager', 'stock.adjust'),
  ('manager', 'packaging.read'),
  ('manager', 'packaging.write'),
  ('manager', 'suppliers.read'),
  ('manager', 'suppliers.write'),
  ('manager', 'purchases.read'),
  ('manager', 'purchases.write'),
  ('manager', 'purchases.receive'),
  ('manager', 'clients.read'),
  ('manager', 'clients.write'),
  ('manager', 'sales.read'),
  ('manager', 'sales.write'),
  ('manager', 'sales.cancel'),
  ('manager', 'payments.read'),
  ('manager', 'payments.write'),
  ('manager', 'deliveries.read'),
  ('manager', 'deliveries.write'),
  ('manager', 'vehicles.read'),
  ('manager', 'vehicles.write'),
  ('manager', 'reports.view'),
  ('manager', 'reports.export'),
  ('manager', 'alerts.read'),
  ('manager', 'alerts.manage'),
  ('manager', 'users.read'),
  ('manager', 'settings.read'),
  
  -- Cashier permissions
  ('cashier', 'dashboard.view'),
  ('cashier', 'products.read'),
  ('cashier', 'stock.read'),
  ('cashier', 'packaging.read'),
  ('cashier', 'clients.read'),
  ('cashier', 'clients.write'),
  ('cashier', 'sales.read'),
  ('cashier', 'sales.write'),
  ('cashier', 'payments.read'),
  ('cashier', 'payments.write'),
  ('cashier', 'alerts.read'),
  
  -- Warehouse Keeper permissions
  ('warehouse_keeper', 'dashboard.view'),
  ('warehouse_keeper', 'products.read'),
  ('warehouse_keeper', 'stock.read'),
  ('warehouse_keeper', 'stock.write'),
  ('warehouse_keeper', 'stock.adjust'),
  ('warehouse_keeper', 'packaging.read'),
  ('warehouse_keeper', 'packaging.write'),
  ('warehouse_keeper', 'purchases.read'),
  ('warehouse_keeper', 'purchases.receive'),
  ('warehouse_keeper', 'deliveries.read'),
  ('warehouse_keeper', 'deliveries.write'),
  ('warehouse_keeper', 'vehicles.read'),
  ('warehouse_keeper', 'alerts.read')
ON CONFLICT (role, permission) DO NOTHING;
